apiVersion: v1
kind: Pod
metadata:
  name: web-test-topo
  namespace: emojivoto
  labels:
    app: web
spec:
  schedulerName: topo-scheduler
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
