apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-like-default
  namespace: emojivoto
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
      evaluation-run: default
  template:
    metadata:
      labels:
        app: web
        evaluation-run: default
        evaluation-role: web-like
    spec:
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "700m"
            memory: "256Mi"
